version: "3.9"

services:
  backend:
    build:
      context: ./
    container_name: alpaca-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: unless-stopped
